Repository scs/smartmeter-datacollector, pull requests merged in 2021-09, with the labels that each got.

#5 Bugfix/optimizations
  smartmeter_datacollector/app.py
  smartmeter_datacollector/collector.py
  smartmeter_datacollector/config.py
  smartmeter_datacollector/factory.py
  smartmeter_datacollector/sinks/data_sink.py
  smartmeter_datacollector/sinks/logger_sink.py
  smartmeter_datacollector/sinks/mqtt_sink.py
  smartmeter_datacollector/smartmeter/cosem.py
  smartmeter_datacollector/smartmeter/hdlc_dlms_parser.py
  smartmeter_datacollector/smartmeter/iskraam550.py
  smartmeter_datacollector/smartmeter/lge450.py
  smartmeter_datacollector/smartmeter/meter.py
  smartmeter_datacollector/smartmeter/meter_data.py
  smartmeter_datacollector/smartmeter/reader.py
  smartmeter_datacollector/smartmeter/reader_data.py
  smartmeter_datacollector/smartmeter/serial_reader.py
Labels: enhancement

#6 add basic documentation to README.md
  README.md
Labels: documentation

#7 Feature/tests
  .github/workflows/python-code-checks.yml
  Pipfile
  Pipfile.lock
  tests/__init__.py
  tests/test_collector.py
  tests/test_config.py
  tests/test_hdlc_dlms_parser.py
  tests/test_lge450.py
  tests/test_meter_data.py
  tests/test_mqtt_sink.py
  tests/utils.py
Labels: enhancement

#8 Feature/gurux update
  Pipfile
  Pipfile.lock
  setup.py
  smartmeter_datacollector/smartmeter/hdlc_dlms_parser.py
Labels: enhancement

#9 clear also dlms data buffer if hdlc buffer gets too large
  smartmeter_datacollector/smartmeter/hdlc_dlms_parser.py
Labels: bugfix
